//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTest.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiTest.Core.Messages.MessageServices", typeof(MessageServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad headers.
        /// </summary>
        public static string BadHeaders {
            get {
                return ResourceManager.GetString("BadHeaders", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Process.
        /// </summary>
        public static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        public static string KOResponseGenerate {
            get {
                return ResourceManager.GetString("KOResponseGenerate", resourceCulture);
            }
        }
        
       
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el cliente.
        /// </summary>
        public static string NotFoundPerson {
            get {
                return ResourceManager.GetString("NotFoundPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SESSION_IN.
        /// </summary>
        public static string OkResponseGenerate {
            get {
                return ResourceManager.GetString("OkResponseGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: process complete user not found.
        /// </summary>
        public static string OKResponseGenerate204 {
            get {
                return ResourceManager.GetString("OKResponseGenerate204", resourceCulture);
            }
        }
        
        
    }
}
